---
 #tasks file for master
- name: initialize the k8s cluster
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16

- name: install calico pod network
  shell: kubectl apply -f https://docs.projectcalico.org/v3.8/manifests/calico.yaml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf

- name: generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  
- name: copy join command to local file 
  become: false
  local_action: copy content="{{join_command.stdout_lines[0]}}" dest="./join-command"

- name: make directory for kube configuration
  file:
    path: /home/kubeuser/.kube
    state: directory

- name: setup kubeconfig for kube_user
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/kubeuser/.kube/config
    owner: kubeuser
    remote_src: yes