---
# tasks file for docker
- name: install packages to allow apt to use repository over HTTPS
  apt: name={{item}} state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker's Official GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add Docker APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: update apt cache
  apt: update_cache=yes

- name: install docker ce and cotnainerd
  apt: 
    name: "{{item}}"
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  notify: docker status
  
- name: enable docker to start on boot
  systemd:
    name: docker
    enabled: yes

- name: add kube_user to docker group
  user:
    name: kube_user
    group: docker
  